# Generated by Django 3.2.2 on 2021-05-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userauthtokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthtokens',
            name='timestamp',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
