# Generated by Django 3.2.2 on 2021-05-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userauthtokens_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('menteeType', models.CharField(max_length=50)),
                ('firstActivity', models.CharField(max_length=50)),
                ('secondActivity', models.CharField(max_length=50)),
                ('thirdActivity', models.CharField(max_length=50)),
                ('fourthActivity', models.CharField(max_length=50)),
                ('fifthActivity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('mentorType', models.CharField(max_length=50)),
                ('firstActivity', models.CharField(max_length=50)),
                ('secondActivity', models.CharField(max_length=50)),
                ('thirdActivity', models.CharField(max_length=50)),
                ('fourthActivity', models.CharField(max_length=50)),
                ('fifthActivity', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='userauthtokens',
            old_name='username',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='_', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
