# Generated by Django 3.2.2 on 2021-05-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210509_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentees',
            name='year',
            field=models.IntegerField(),
        ),
    ]
