# Generated by Django 3.2.2 on 2021-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_mentors_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('familyid', models.IntegerField()),
            ],
        ),
    ]
