# Generated by Django 3.2.2 on 2021-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pairings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('resetToken', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
